;;; Package: COMMON-LISP-USER, Mode: Lisp

(in-package "COMMON-LISP-USER")
 
(defpackage enrico-utilities
  (:nicknames "EU" utilities)
  (:use "COMMON-LISP")
  (:export "EQUAL*" "CREATE-DIRECTORY"
   "FILTER" "MAPCAN*" "MAP-OVER-HASH-TABLE" "LIST-HASH-TABLE" "MAP-IF" "SET-EQUAL" "SPACES" "LINES"
   "NOTIFY" "YES-OR-NO-MENU""CLASS-NAME" "PERMUTE" "LOAD-FILE-FROM-MENU" "SAME-SYMBOL"
   "FILTER*" "FILTER-ORDERED-LIST" "RIGHT-VALUE" "RIGHT-VALUE*" "LEFT-VALUE"
   "LEFT-VALUE*""PUSH-INTO-ALIST" "CONS*" "APPEND*"
   "LAST-ELEMENT" "UNION*" "PRINT-WITH-SPACES""MINIMAL-SET" "MAXIMAL-SET" "PAIRIFY"
   "SUBSTITUTE-EL"
   "TRANSLATE-TREE" "ORDER-FILTER" "ENSURE-VANILLA-CLASS"
   "ENSURE-VANILLA-CLASS2" "INIT-ARG-VALUE" "LIST-CLASS-SLOTS"
   "SUBCLASS-OF?" "REMOVE-CLASS" "FIND-CLASS-SLOT" "FIND-CLASS-DIRECT-SLOT"
   "CLASS-SLOT-VALUE""CLASS-PRECEDENCE-LIST"
   "SUBCLASSES" "DIRECT-SUBCLASSES" "DIRECT-SUPERCLASSES" "CLEAR-SUBCLASSES-SLOT"
   "REMOVE-SUBCLASS" "CHOOSE-ALIST-VALUES" "STRING-APPEND" "SUBSTRING" "REPLACE-CHAR-WITH-STRING" "URL?"
   "RECORD-SOURCE-FILE" "SOURCE-FILES" "CURRENT-FILE" "SUPPRESSING-WARNINGS"
   "*DEFAULT-UTIL-PATHNAME*""*DEFAULT-UTIL-LOAD-FILE*"))
